---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to display hostname
    command: hostname -f
    register: myresult
  - name: display myresult value
    debug:
       msg: "{{myresult}}"
  
  - name: install git
    apt:
      name: git
    when:  myresult.stderr ==""
  - name: install tree
    apt:
      name: tree
    when:  myresult.stderr !=""

