---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install webserver on myubuntu
    apt:
      name: "{{webserverforUbuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on myubuntu
    service:
      name: "{{webserverforUbuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: install webserver on myredhat 
    yum:
      name: "{{webserverforRedhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on myredhat
    service:
      name: "{{webserverforRedhat}}"
      state: started
    when: ansible_os_family =="RedHat"